const dataUser = [
    {
        // id: 1,
        username: "IT0001",
        firstName: "คฑาวุธ",
        lastName: "ไผ่ตาแก้ว",
        position: "IT-Support",
        status: 1,
    },
    {
        // id: 2,
        username: "IT0002",
        firstName: "สีขรินทร์",
        lastName: "บุญญานุสรณ์",
        position: "IT-Support",
        status: 1,
    },
    {
        // id: 3,
        username: "E0001",
        firstName: "บุญญาพร",
        lastName: "บุญญานุสรณ์",
        position: "Software Engineer",
        status: 1,
    },
    {
        // id: 4,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 5,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 6,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 7,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 8,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 9,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 10,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 11,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 12,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 13,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 14,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 15,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 16,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 17,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 18,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 19,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
    {
        // id: 20,
        username: "U0001",
        firstName: "นภาพร",
        lastName: "อันตราย",
        position: "User",
        status: 1,
    },
];

export default dataUser;